### ISSUE TITLE
Events part scrollbars

### ISSUE THREAD

**Issue by Sapoose** [callmearta/clubhouse-desktop#11]
There is a scrollbar for height.
![image](https://user-images.githubusercontent.com/60824904/111904936-44269100-8a5a-11eb-93f3-114651ec2dc9.png)
and i actually tried to fix it by developer tools but it doesn't turn on

**Comment by callmearta** [comment]
Developer tools is disabled in prebuilt versions. You can enable it by running the source code manually.
About that scrollbar i'm completely aware and i'm thinking to change the events section completely.
