### ISSUE TITLE
There are bugs that can be voice-chatted after logging out

### ISSUE THREAD

**Issue by dhje0ng** [callmearta/clubhouse-desktop#13]
I was able to find bugs in the application. Even if you log out after entering the chat room, you can continue to talk without losing your voice connection.

**Comment by callmearta** [comment]
Yes i know that. That's not application bug. It's because clubhouse's voice service is on Agora and they have only handled such procedures in client side. I think they're also aware of this bug and they're trying to fix it.

**Comment by callmearta** [comment]
Hi. thanks for pointing that out. since it's not something vital, i'll handle it in the future.
