### ISSUE TITLE
How to build

### ISSUE THREAD

**Issue by miladini** [callmearta/clubhouse-desktop#15]
Hi Arta,

Will it be possible for you to include a documentation around how to build this client (particularly on Linux)?
This will help those who like to contribute (myself included) with getting started quicker.

**Comment by callmearta** [comment]
I added manual to run the project locally. Also a section for building information and i hope no one builds it and publishes it and gives credit to themselves.

**Comment by miladini** [comment]
Hi Arta,

Thanks for sharing. I am going to try it when I get a chance.

As for the credit, I am sure you can licence your work in such a way that can protect any rights that you like to preserve.
