### ISSUE TITLE
Poor sound quality

### ISSUE THREAD

**Issue by omerdn1** [callmearta/clubhouse-desktop#16]
Hey bud, lovely piece of work you got here!

I noticed that the speaker sound quality in this app is substantially lower than in the native mobile app.

Is this a known issue?

**Comment by callmearta** [comment]
Hi. Thank you. Yup that's a known issue which i really would have loved to fix but there's wasn't any solution for it. I tried many many things but no luck. If you found any solution I'd be more than happy to fix it.

**Comment by omerdn1** [comment]
@callmearta I've used the Android alternative over at https://github.com/grishka/Houseclub and I'm pretty sure their sound quality is on par with the mobile app, so you can check to see how they've implemented the webrtc protocol there. (link to the implementation: https://github.com/grishka/Houseclub/blob/master/Houseclub/src/main/java/me/grishka/houseclub/VoiceService.java)

I'll also have a look during the weekend.

Thanks for the quick reply and for your awesome work!

**Comment by callmearta** [comment]
@omerdn1 I've looked at it so many times before. The voice issue is not from my code and it's because of Agora SDK which provides voice service. I'm forced to use their web SDK and from that point, there's not much i can do for the quality. It's all done by it's SDK.
Thank you
