### ISSUE TITLE
resize the window in ubuntu

### ISSUE THREAD

**Issue by efarzadkhani** [callmearta/clubhouse-desktop#17]
hi, thanks for this
i can`t resize the view and its always full screen.is there any solution for that?

**Comment by miladini** [comment]
I was struggling with the same problem, and also trying to move the window. 

* For resizing the window, I tweaked the following object:
https://github.com/callmearta/clubhouse-desktop/blob/150ba375cdb917651c57b993b851aaf501f9fd75/index.js#L31-L50

* For moving the window, do it the old-fashion way from the old days of Windows:
`Alt+Space` -> `Move`
