### ISSUE TITLE
Using Universal Analytics to Track Viewers

### ISSUE THREAD

**Issue by miladini** [callmearta/clubhouse-desktop#18]
Hi Arta,

I was wondering if the `universal-analytics` package is used to collect information about the visitor's behavior? Nothing wrong with it as it's already open source, just trying to confirm.

https://github.com/callmearta/clubhouse-desktop/blob/150ba375cdb917651c57b993b851aaf501f9fd75/app/main.js#L7

https://github.com/callmearta/clubhouse-desktop/blob/150ba375cdb917651c57b993b851aaf501f9fd75/app/main.js#L129-L138

By the way, I was able to build the client locally on linux. Thank you for the instructions.

**Comment by callmearta** [comment]
Hello,
Yes it's used to only track the number of installs and users. I don't even collect information about users behavior as you can see in the code.

**Comment by miladini** [comment]
Thanks Arta @callmearta
