### ISSUE TITLE
when I visit a profile of someone in a room and return to the room again it be such as I have leaved the room and join it again

### ISSUE THREAD

**Issue by BrMky** [callmearta/clubhouse-desktop#19]
Hi 
when I visit a profile of someone in a room and return to the room again it be such as I have leave the room and join it again.

And Sometimes I just can't raise my hand up

And I suggest you add home page icon in the rooms too.

Thx, and sorry cuz of my English 😅

**Comment by callmearta** [comment]
Hi
Homepage icon isn't needed indeed because you have access to the rooms on the left side.
Raisehand wouldn't work in rooms where it's disabled.
