### ISSUE TITLE
Add Windows and Linux version

### ISSUE THREAD

**Issue by mehdiraized** [callmearta/clubhouse-desktop#2]
pls add Windows and Linux version

**Comment by callmearta** [comment]
New linux version would be added soon.
Windows version though may not be available soon, because i haven't got any test devices to debug it.

**Comment by zoghal** [comment]
سلام، ضمن تشکر خواستم به اطلاعتون برسانم، من نسخه لینوکسی رو به ویندوزی تبدیل کردم و مشکلی خاصی مشاهده نکردم، هرچند بنده هیچ گفتگویی نداشتم، فقط اتاق‌ها رو پایین بالا کردم. اگر برای تست کمک نیاز داشتید من در خدمتم :)

![image](https://user-images.githubusercontent.com/174688/111053987-f7512200-847d-11eb-8ac2-bc8278b0c90b.png)

**Comment by callmearta** [comment]
سلام وقت بخیر. ممنون که تست کردید. بله مشکلی توی این مراحل خودم هم نداشتم و داخل اتاق‌ها فقط صدا نمیومد و نمی‌رفت. اونم حل شده و دوستان تست گرفتند. احتمالا نسخه ویندوز رو هم به زودی می‌ذارم. تشکر
