### ISSUE TITLE
Clubhouse font is not readable for Farsi letters in Linux

### ISSUE THREAD

**Issue by Gictorbit** [callmearta/clubhouse-desktop#23]
Clubhouse font is not readable for Farsi letters in Linux
I think you are using Clubhouse on `macOS` based on screenshot in `README`,  and Farsi font is pretty there because of default font system, in Linux we don't have macOS fonts and it's not readable

![image](https://user-images.githubusercontent.com/34630603/113922998-41b78b80-97fd-11eb-9fd4-a58bdde7d354.png)

**Comment by callmearta** [comment]
I haven't came across any free to use Farsi fonts which also has a good English font too. If you know one let me know.

**Comment by Gictorbit** [comment]
I think [Vazir](https://github.com/rastikerdar/vazir-font) would be a great choice, it's open source and supports both English and Farsi letters. that's why Telegram Desktop uses vazir

**Comment by Gictorbit** [comment]
I solved this issue by adding fonts config file in config directory
path: `~/.config/fontconfig/fonts.conf`

```
<?xml version='1.0'?>
<!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
<fontconfig>

 <match>
  <edit mode="prepend" name="family">
   <string>Vazir</string>
  </edit>
 </match>

 <dir>~/.local/share/fonts</dir>
 <dir>/usr/share/fonts/</dir>
 <dir>~/.fonts</dir>

</fontconfig>

```
