### ISSUE TITLE
Unable to follow

### ISSUE THREAD

**Issue by eamirgh** [callmearta/clubhouse-desktop#24]
There is no UI to follow people.

**Comment by miladini** [comment]
I changed the following line
https://github.com/callmearta/clubhouse-desktop/blob/150ba375cdb917651c57b993b851aaf501f9fd75/app/views/user.js#L324

into:
```javacript
                    <button class="btn-primary mt-3" @click="follow" v-if="!isMe && user.user_profile.notification_type !== 2">Follow</button>
```

and it worked for me.

**Comment by eamirgh** [comment]
@miladini why don't you create a pull request?

**Comment by miladini** [comment]
@eamirgh 

There you go! https://github.com/callmearta/clubhouse-desktop/pull/25

**Comment by eamirgh** [comment]
@miladini thank you so much 🍻

**Comment by callmearta** [comment]
Follow button should be handled by checking user's data which contains followings ids, not notification type. Before it was alright to check it with notification type but not anymore. If you'd like to do a pull request i appreciate it.
