### ISSUE TITLE
Keep loading

### ISSUE THREAD

**Issue by edchidna** [callmearta/clubhouse-desktop#30]
After tried login on windows and test it work propely except create a club room, and i login in iphone and created room the windows clubhouse keep loading nothing happened. Clubhouse on iphone still working fine

**Comment by callmearta** [comment]
I think the problem is because of the logging in on your Iphone. Clubhouse doesn't allow multi login sessions since a month ago and now if you login using another device you'll be logged out on others.

**Comment by edchidna** [comment]
I've tried to logout from my iphone, but still keep loading what should i do if i want to use clubhouse on windows?

On 13 Apr 2021, at 14.12, callmearta ***@***.***> wrote:

﻿

I think the problem is because of the logging in on your Iphone. Clubhouse doesn't allow multi login sessions since a month ago and now if you login using another device you'll be logged out on others.

**Comment by callmearta** [comment]
login again on windows and then use it

**Comment by edchidna** [comment]
I can't even login, everytime i launch the clubhouse it end up stick with loading like this[cid:27517306-BD5B-4911-A007-3B1217622DFA-L0-001]


On 13 Apr 2021, at 14.56, callmearta ***@***.***> wrote:

﻿

login again on windows and then use it

**Comment by callmearta** [comment]
Try to delete the electron cache. Use the following link on Stackoverflow to do so. Then your windows Clubhouse would work fine.
https://stackoverflow.com/questions/31446782/how-to-clear-the-cache-data-in-electronatom-shell

**Comment by edchidna** [comment]
Ok thank you so much for the support.

On 13 Apr 2021, at 15.22, callmearta ***@***.***> wrote:

﻿

Try to delete the electron cache. Use the following link on Stackoverflow to do so. Then your windows Clubhouse would work fine.
https://stackoverflow.com/questions/31446782/how-to-clear-the-cache-data-in-electronatom-shell

**Comment by callmearta** [comment]
No problem.
