### ISSUE TITLE
please support:  auto updating Electron app

### ISSUE THREAD

**Issue by zoghal** [callmearta/clubhouse-desktop#34]
درود مجدد و تشکر از بابت زحماتی که می‌کشید. می‌خواستم پیشنهاد بدم اگر ممکن است امکان بروزرسانی اتوماتیک را هم اضافه کنید، تا همیشه بتونیم آخرین نسخه رو استفاده کنیم.

https://www.electron.build/auto-update
https://github.com/ArekSredzki/electron-release-server
https://github.com/iffy/electron-updater-example

**Comment by callmearta** [comment]
سلام وقت بخیر. من امتحان کردم اضافه کردن اتو آپدیت رو اما برای سیستم عامل‌های مک نیاز به اکانت دولوپر اپل هست و اپلیکیشن باید ساین بشه حتما و به همین دلیل من نتونستم اتو آپدیت برای مک رو اضافه کنم. از طرفی هم به دلیل این‌که تنها سیستم عامل مک رو در اختیار دارم نمی‌تونم برای سیستم عامل‌های دیگه این ویژگی رو تست کنم. اگر برای شما امکان پذیر بود خوشحال میشم که PR بسازید بابتش.

**Comment by ArturMakly** [comment]
plus 1
