### ISSUE TITLE
Invalid token

### ISSUE THREAD

**Issue by vlna232** [callmearta/clubhouse-desktop#35]
Hi,
I was running this app for a couple of days  without any issue. Now I've got error message that token is invalid. How can I reset the token?
Thanks
Vladimir

**Comment by callmearta** [comment]
Hi,
Try to clear the cache data of application. See link below for instructions:
https://stackoverflow.com/questions/31446782/how-to-clear-the-cache-data-in-electronatom-shell

**Comment by vlna232** [comment]
Hi,
thnx,
