### ISSUE TITLE
Running in browser

### ISSUE THREAD

**Issue by 0x41mmarVM** [callmearta/clubhouse-desktop#37]
Hi!
Thanks for the amazing work.
Is this possible to run in a web browser? I've been looking around in the code and the network connections, and nothing seems like it's Electron-specific.

**Comment by callmearta** [comment]
Hello mate, thank you.
Yes it is possible. But the problem is CORS error in clubhouse apis. If you manage some backend code for proxying clubhouse apis then it would work fine, but then some trust issues would occur because you're using a third party server and there would be security concerns.

**Comment by 0x41mmarVM** [comment]
Interesting..
So roughly speaking I'd replace the API hostnames with my own server's, run a reverse proxy for these hostnames, and build the web app for the browser. Sounds about right?

**Comment by callmearta** [comment]
Yes

**Comment by 0x41mmarVM** [comment]
Awesome, thanks!
