### ISSUE TITLE
Scrollbar improvment

### ISSUE THREAD

**Issue by saman** [callmearta/clubhouse-desktop#4]
I can see some scrollbars; I didn't see them before.
It would be great if you manage to change them to a native-like scrollbar.

Here is a screenshot:
![Screenshot 2021-03-13 at 5 56 15 PM](https://user-images.githubusercontent.com/1576246/111037744-cba24d80-8425-11eb-8a51-379c34d2c60f.png)

**Comment by callmearta** [comment]
You see, the problem is that same source code is used for the linux version and because of that, many users would fail to scroll horizontally. So i had to let them be visible :)) If you've got any advice on how to make scrollbars better which also works on linux + windows i'll appreciate.

**Comment by saman** [comment]
I guess you can retrieve the OS from the `os` package.
You might need to add the scrolls only for Linux.

See this:
https://www.freecodecamp.org/news/how-to-write-os-specific-code-in-electron-bf6379c62ff6/

**Comment by callmearta** [comment]
Yes i know it's possible to retrieve OS. but sadly it's not possible in CSS. I might have to rewrite the component for that matter and i think there's still more important things to implement.
Thank you btw

**Comment by saman** [comment]
Just in case, take a look at [Dynamic Styling in Electron](https://www.geeksforgeeks.org/dynamic-styling-in-electronjs/). It's possible to add a specific CSS style so that you may customize it based on OS.

**Comment by callmearta** [comment]
Thank you. i'll check it out.
