### ISSUE TITLE
ارور not valid token

### ISSUE THREAD

**Issue by Caligulation** [callmearta/clubhouse-desktop#42]
سلام، خسته نباشی
من یک بار تونستم وارد بشم و به خوبی کار می کرد. اما حالا که می خوام وارد بشم ارور میده به این شکل: 
not valid token
و ازم می خواد که ساین اوت کنم و مجدد وارد بشم اما چیزی روی صفحه لود نمیشه.
آیا راه حلی وجود داره براش؟
مرسی

**Comment by callmearta** [comment]
در نسخه آینده مشکل برطرف میشه
