### ISSUE TITLE
Unable to invite people to rooms after room is started

### ISSUE THREAD

**Issue by stultus** [callmearta/clubhouse-desktop#49]
When we invite a person to a room after the room is created, it fails - even if we are following the person (and the person follows us)
![Screenshot from 2021-06-01 11-27-47](https://user-images.githubusercontent.com/328309/120284321-c2fd3d00-c2d9-11eb-8f13-e67ccd005746.png)

**Comment by callmearta** [comment]
The error is returned from Clubhouse's api. I'll check it when i got the time but at the time being feel free to check the network tab to see if request headers are correctly sent.

**Comment by callmearta** [comment]
New PR was accepted. try to see if the problem still occurs.

**Comment by stultus** [comment]
I can confirm that this issue is resolved.
