### ISSUE TITLE
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)

### ISSUE THREAD

**Issue by rabinniroula** [callmearta/clubhouse-desktop#51]
Probably some graphics driver error. It would be awesome if you guys added an updated linux binary in releases. The graphic is messed up on my manjaro for the older binary.

**Comment by ntang99** [comment]
I have the same problem. I installed libva-dev and vainfo. When I ran vainfo, I got same error message. So it looks my linux box does not support the graphic driver.

**Comment by callmearta** [comment]
Honestly i don't know what's going on there cause i don't have a linux based device but last time i tested everything was working fine. If you're able to fix the error you're facing feel free to do a PR.

**Comment by ntang99** [comment]
Change the node version from 12 to 14 may get rid of the problem.
