### ISSUE TITLE
Linux Installation Guide

### ISSUE THREAD

**Issue by PEMIDI** [callmearta/clubhouse-desktop#6]
I want to install this on my debian linux. but I don't understand the installation procedure.
what's a good solution to that?

**Comment by callmearta** [comment]
For only installing and using it, you don't need the source code. Head to releases and download the linux version

**Comment by MrMohammadY** [comment]
I downloaded the linux release but i don't know how to install that
@callmearta

**Comment by callmearta** [comment]
There's no need to install anything. Just extract the .zip file and run it using ./clubhouse
