### ISSUE TITLE
ui issues, always reloading

### ISSUE THREAD

**Issue by sathish-dream-ai** [callmearta/clubhouse-desktop#61]
![ch](https://user-images.githubusercontent.com/46743355/121128686-6c4bb200-c849-11eb-805f-83a2c737374f.png)

It is showing reloading for the past five days.

**Comment by callmearta** [comment]
Your token is invalid because of you've logged in on some other device. You need to clear localStorage. It's been mentioned many times before and i've answered them in closed issues. lookup before opening new issue
