### ISSUE TITLE
Login seems to consistently fail

### ISSUE THREAD

**Issue by 0x41mmarVM** [callmearta/clubhouse-desktop#62]
Hi,
As of today, all my login attempts are failing. I do not receive a text code, but I do receive calls. Once I type the code, the result in the console is

`{success: true, is_verified: false, number_of_attempts_remaining: 3}`

I've tried multiple machines and multiple accounts, using the main branch.

**Comment by satyaakam** [comment]
i am facing the same issue Desktop app is not able to verify the code i heard

**Comment by 0x41mmarVM** [comment]
It seems the version of the API on which seia-soto/clubhouse-api was based can no longer be used to log in. None of the public implementations seems to be working anymore.

**Comment by callmearta** [comment]
try to wait for sms and after about a minute try sms again and after that request a call and see if it works or no

**Comment by huanyue2019** [comment]
Hello, I would like to ask a login question.I enter the number here and click next and it keeps showing that the interface has timed out.

`FetchError: request to https://www.clubhouseapi.com/api/start_phone_number_auth failed`

**Comment by callmearta** [comment]
It's because clubhouse's api doesn't send you a response. The api could have been censored in your ISP or your internet isn't stable. at any of these situations the problem is you not getting a response.

**Comment by ujj-w-a-l** [comment]
I am facing the same problem. I think they have made changes to API.

**Comment by gunalabs** [comment]
> Hi,
> As of today, all my login attempts are failing. I do not receive a text code, but I do receive calls. Once I type the code, the result in the console is
> 
> `{success: true, is_verified: false, number_of_attempts_remaining: 3}`
> 
> I've tried multiple machines and multiple accounts, using the main branch.

The exact thing happened for me in the clubhouse snap unofficial app.

**Comment by callmearta** [comment]
@gunalabs That's the same app. Just someone had the time to deploy my code to snapcraft.

**Comment by gunalabs** [comment]
> @gunalabs That's the same app. Just someone had the time to deploy my code to snapcraft.

😂 Cool!

**Comment by Shabinder** [comment]
+ 1 Login fails even after receiving the code on call, Code is never received as SMS, India +91

**Comment by aneeskA** [comment]
Another app `Clubdeck` works correctly. I love `cloubouse-desktop` UI. So trying again and again to get it to work. Any one has a solution?

**Comment by aneeskA** [comment]
This is the error coming up in the console. `Invalid request` is seen in it.

<img width="538" alt="image" src="https://user-images.githubusercontent.com/514419/124416010-a7230600-dd73-11eb-82ba-e9734f359e46.png">

**Comment by aneeskA** [comment]
The issue is also seen in latest `master`.

**Comment by aneeskA** [comment]
@callmearta Can you please take a look?

**Comment by callmearta** [comment]
@aneeskA Sorry i haven't got much time now to check it. As far as i know, Clubhouse has added a new property named rc_token ( i think ) which needs to be sent on login request and this version of the app is not sending it so the login fails. If you can find out what it is and fix it feel free to do a pull request.
