### ISSUE TITLE
Code received via Call but not accepting

### ISSUE THREAD

**Issue by itsmeshibintmz** [callmearta/clubhouse-desktop#64]
![Screenshot 2021-06-18 065159](https://user-images.githubusercontent.com/52344717/122491475-b8dd7d00-d001-11eb-8b14-2d78c42d3a4e.png)

I get code from the call, but when I verify code it shows a loading screen but refreshes back to the same verification page.

**Comment by callmearta** [comment]
It seems that there's been some changes in Clubhouse's apis. I don't have the time to check it out right now but maybe in future i'd do a new release which would fix the issue. Closing this issue as there's another one open right now with the same problem explained
