### ISSUE TITLE
cannot verify with six digit verification code.

### ISSUE THREAD

**Issue by sanjeebSubedi** [callmearta/clubhouse-desktop#67]
The verification code sent from the server is of  digits but the desktop app only allows 4 digit code be verified.

**Comment by aterban158** [comment]
hi. i can't get sms code or call for verify ! how can fix it?

**Comment by skyonedot** [comment]
Yeah. I meet this problem too. the server is of digits but the desktop app only allows 4 digit code be verified.

**Comment by ziggipiggi** [comment]
> The verification code sent from the server is of digits but the desktop app only allows 4 digit code be verified. 

Did you received verification code?

**Comment by psvnlsaikumar** [comment]
Tried changing the code as well, apparently, the API was proving an error code, stating that the request params were incorrect. Need to dig deeper. However, if anyone is interested in having a look at it, feel free.
https://github.com/callmearta/clubhouse-desktop/blob/af05cfca96b17bea2c507e57ab792f245da7a815/app/views/verify.js#L43

**Comment by callmearta** [comment]
Needs new parameters. Try to catch packets on the app before it's being sent to clubhouse's api so you can find new parameters that are needed to be sent.

**Comment by psvnlsaikumar** [comment]
@callmearta I guess there is something wrong with the API. or either somehow I was unable to use them. I've tried hitting the endpoints with postman, and have recieved the expected response, but my device did not recieve and OTP for me to try the /complete_phone_number_auth endpoint

I've used this collection for verifying the API https://documenter.getpostman.com/view/2651915/TzCQa6Wx

**Comment by callmearta** [comment]
Try to capture packets in the official mobile apps and see what's changed.
