### ISSUE TITLE
Is ClubhouseAPI no longer working?

### ISSUE THREAD

**Issue by ziggipiggi** [callmearta/clubhouse-desktop#69]
Hello
I have been searching the internet for a month to find the right answer.
All Unofficial Clubhouse projects stopped. They have not updated since 6 months ago.

Most developers have written that they are no longer able to continue developing because they do not have enough free time to maintain. Some have said that the Android version has been released and there is no need to continue their project.

The interesting thing is that all of this happened together, but no one is saying exactly why the API is not working. Is it because of the pride of programmers who do not tell the truth?

I do not know who accessed ClubhouseAPI and how and published it for the first time. Did the Clubاouse official website make it available to the public before or someone hacked?

I'm looking to use the Clubhouse API. For example, I used "start_phone_number_auth" and i got success but did not receive a verification code. I think this because the headers parameters, this is my headers:

```
    let headers: object = {
      'User-Agent': 'clubhouse/526 (iPhone; iOS 14.7.1; Scale/2.00)',
      'CH-Languages': 'en-US',
      'CH-Locale': 'en_US',
      'CH-AppVersion': '1.0.4',
      'CH-AppBuild': '526',
      'CH-DeviceId': uuidv4().toUpperCase(),
      'CH-UserID': '(null)',
      'Content-Type': 'application/json; charset=utf-8',
      'Accept-Encoding': 'gzip, deflate',
      'Accept-Language': 'en-US;q=1',
      'Connection': 'close',
      'Host': 'www.clubhouseapi.com',
      'Access-Control-Allow-Origin': '*',
    };
```
BODY: 

`data: {phone_number: "+11234567890" }`  // I tested it with real number.

Response:
`{"success":true,"is_blocked":false,"error_message":null,"send_rc_token":true}`

So far, it seems everything is correct. But not received verification code via SMS. I checked it with many phone numbers, New phone numbers that did not have a Clubhouse account before, The number registered before and previously had account in Clubhouse. Even i tested with blocked numbers but returned success true and is_blocked false.

I removed plus before phone number for testing and i got this:
`{"success":false,"is_blocked":false,"error_message":"Your phone number is incorrect. Please try again."}`

Any idea? Is wrong headers or body? Maybe API is not working for 6 numbers verification code or added new API with new headers/body parameters?

The point is, Only Clubdeck (Unofficial clubhouse version) still working. How does the developer have access to the API changes? 

Most social media have provided their API reference to developers such as Facebook, Instagram, Telegram, etc.
https://developers.facebook.com
https://developer.twitter.com/en/docs/api-reference-index
https://core.telegram.org

I don't know why Clubhouse opposes other developers activity on their app.

I sent mail several times to the support of Clubhouse about the activities of the developers and the API of Clubhouse. But I have not received any answer so far. Clubhouse support does not answer any problems or request. I saw a lot of people on sites like reddit and twitter who complained the lack of response from Clubhouse support.

Does anyone have new information on how to use Clubhouse API?

Please help

Thank you in advance

**Comment by callmearta** [comment]
Hi
The reason Clubdeck is still alive and doing updates is the fact that it is making money.
Other unofficial apps have not got any financial support so it's rational for the developers to stop developing them further more.
About the api changes, I don't think Clubdeck has access to api changes. But it's not that difficult to monitor requests sent from an app to understand new api changes.
About the problem happening in my app, the thing is you need to send new parameters like rc_token and another parameter which i haven't got time to check.
Anyways, if you did manage to reverse engineer the app and get the new api out of it and also did develop anything on my app to fix current problem about verification, feel free to do a pull request and i'll be happy to accept.
