### ISSUE TITLE
Show message if username is already taken

### ISSUE THREAD

**Issue by mitar** [callmearta/clubhouse-desktop#7]
It looks like if username is already taken, pressing submit button looks like it does not do anything. Only after I changed it to username which does not exist, it went through. So some message saying that username is already taken would be great.

BTW, awesome work!

**Comment by callmearta** [comment]
Thank you, If any error is returned from clubhouse's backend, the app will show you a native os notification containing the message.

**Comment by mitar** [comment]
I didn't see any notification on Linux. Maybe because the app is always in full screen so notifications might be hidden?
